### ISSUE TITLE
Missing argument 'exit code' argument in mock function invocation

### ISSUE THREAD

**Issue by teehemkay** [PatrickF1/fzf.fish#123]
https://github.com/PatrickF1/fzf.fish/blob/8a299b47d89fef49d5d548ae1bb8ba53452da201/tests/preview_file/custom_dir_preview.fish#L2

The test is failing. The reason seems to be that the `mock` function requires a `[exit code]` argument before the `[executed code]` argument provided.

https://github.com/matchai/fish-mock#usage

This issue appears in many places throughout the test code base.
e.g. in all the files in the `tests/search_current_dir/` directory for example.

```
return: Argument 'echo file.txt' is not a valid integer

~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish (line 57): 
    return $exit_code
    ^
in function 'mocked_exa_fn_.' with arguments '.'
	called on line 1 of file ~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish
in function 'exa' with arguments '.'
	called on line 1 of file ~/hacking/fzf.fish/functions/__fzf_preview_file.fish
in function '__fzf_preview_file' with arguments '.'
	called on line 1 of file ~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish
in command substitution
	called on line 3 of file ~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish

(Type 'help return' for related documentation)
test: Missing argument at index 2

Standard input (line 9): 
                if test $argv
                   ^
in function '@test' with arguments 'correctly\ uses\ custom\ command\ to\ preview\ directories = file.txt'
	called on line 4 of file ~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish

(Type 'help test' for related documentation)
not ok 1 correctly uses custom command to preview directories
  ---
    operator: =
    expected: 
    actual: file.txt
    at: ~/hacking/fzf.fish/tests/preview_file/custom_dir_preview.fish:4
  ...
```

**Comment by PatrickF1** [comment]
Hi @teehemkay. Oops should have clarified somewhere (but where?) that the mock library I'm using is actually https://github.com/IlanCosman/clownfish. You can see that in the CI file.

**Comment by teehemkay** [comment]
Hi @PatrickF1. Thank you for clarifying that! 
I was mystified by the mock call appearing in the tests and then `fish-mock` was the first result returned when I search for "fish mock" ;-)

**Comment by PatrickF1** [comment]
You're welcome! Are you thinking of helping write tests?

**Comment by teehemkay** [comment]
I'm in the process of integrating this plugin into `nixpkgs` since it now as [native support](https://github.com/NixOS/nixpkgs/pull/107834) for fish plugins. So I wanted to make sure that the tests can run that that they succeed. In the process I've had to understand how the tests where actually run :-)

Oh and btw, yes, I think it would be quite helpful to mention (I would suggest somewhere on the wiki) that `clownfish` is the mock library used. I did search on the wiki but didn't think to look in the CI file.

As to helping writing test, I'd would be really happy to help except I've just learned about the existence of the plugin and have not even used it yet (I was using Jethrokuan/fzf :-)

**Comment by teehemkay** [comment]
BTW I still have 2 tests failing out of 13

Any idea what could be the cause?

I'm on macOS 10.15.7 using `fzf.fish` v5.5 (also tested w/ HEAD), `fish` 3.1.2 and `fishtape` 3.0.1 and `clownfish` 
```
test: Missing argument at index 2

Standard input (line 9): 
                if test $argv
                   ^
in function '@test' with arguments 'doesn\'t\ overwrite\ \$\ when\ replacing\ current\ token\ with\ selected\ variable = \$selection'
	called on line 7 of file ~/hacking/fzf.fish/tests/search_shell_variables/$_in_curr_token.fish

(Type 'help test' for related documentation)
not ok 11 doesn't overwrite $ when replacing current token with selected variable
  ---
    operator: =
    expected: 
    actual: '$selection'
    at: ~/hacking/fzf.fish/tests/search_shell_variables/$_in_curr_token.fish:7
  ...
test: Missing argument at index 2

Standard input (line 9): 
                if test $argv
                   ^
in function '@test' with arguments 'can\ find\ a\ local\ variable = a_local_variable'
	called on line 6 of file ~/hacking/fzf.fish/tests/search_shell_variables/local_var.fish

(Type 'help test' for related documentation)
not ok 12 can find a local variable
  ---
    operator: =
    expected: 
    actual: a_local_variable
    at: ~/hacking/fzf.fish/tests/search_shell_variables/local_var.fish:6
  ...

**Comment by jorgebucaran** [comment]
It's telling you:

> test: Missing argument at index 2

You have a malformed test expression. 

Got a link to the failing test code?

**Comment by teehemkay** [comment]
Thanks @jorgebucaran, for the input, it's much appreciated!

I think I understand the error message but what's puzzling me is that  (to my untrained eye) the code seems legit.

The failing code is at

https://github.com/PatrickF1/fzf.fish/blob/8a299b47d89fef49d5d548ae1bb8ba53452da201/tests/search_shell_variables/%24_in_curr_token.fish#L7

and

https://github.com/PatrickF1/fzf.fish/blob/8a299b47d89fef49d5d548ae1bb8ba53452da201/tests/search_shell_variables/local_var.fish#L6

**Comment by jorgebucaran** [comment]
Both tests will fail unexpectedly if `$actual` is empty. 

Can you try this instead?

```fish
@test "doesn't overwrite \$ when replacing current token with selected variable" "$actual" = "\$selection" 

@test "can find a local variable" "$actual" = a_local_variable 
```

**Comment by teehemkay** [comment]
@jorgebucaran I followed your suggestions and now the tests fails "correctly", thank you.

@PatrickF1 now back to you re: the failing tests :-) 

```
not ok 11 doesn't overwrite $ when replacing current token with selected variable
  ---
    operator: =
    expected: '$selection'
    actual: ''
    at: ~/hacking/fzf.fish/tests/search_shell_variables/$_in_curr_token.fish:7
  ...
not ok 12 can find a local variable
  ---
    operator: =
    expected: a_local_variable
    actual: ''
    at: ~/hacking/fzf.fish/tests/search_shell_variables/local_var.fish:6
  ...
```

**Comment by PatrickF1** [comment]
@teehemkay Hey I think the problem may be that the plugin is out of date locally. Can you run `fisher update patrickf1/fzf.fish`?

**Comment by teehemkay** [comment]
@PatrickF1 I run the tests from a git repo I get the same errors both for v5.5 and for HEAD...

Re: "native support".

Nixpkgs now has features to ease the process of testing and installing fish plugins:
- `fishPlugins` a set that provides ready-to-be installed plugins (currently mostly `pure` and `fishtape` but it's relatively easy to add new ones)
- `buildFishPlugins` a function to help packaging plugins (basically doing what a plugin manager does but )
- `wrapFish` a function to configure a sandboxed `fish` with selected plugins

All that was possible before but required quite a bit of boilerplate, now it's quite straightforward and standardized.

I ❤️ `fisher` but having everything managed by `Nix` is quite nice.

**Comment by teehemkay** [comment]
Oops, I missed that `5.6` was released.

I tested w/ that version but still have the failing tests (and still had to apply @jorgebucaran recommendation above because the tests are still broken ;-)

**Comment by PatrickF1** [comment]
Hey teehemkay, happy to help you debug this. But first, can I get more info on how you installed it and are running the tests? For example, it sounds like you're not using fisher to install it?

**Comment by teehemkay** [comment]
@PatrickF1 thank you, I appreciate it :-) 

here's what I did:

- clone this repo
- using nix, set up a sandbox that basically includes `fish`, `go`, `fzf`, and `bat`, per `fzf.fish` requirements and `fishtape` and `clownfish`
- patch `tests/search_shell_variables/$_in_curr_token.fish` and `tests/search_shell_variables/local_var.fish` (per @jorgebucaran recommendation above)
- run `$ fishtape tests/**.fish`

And here's the output:

```
TAP version 13
ok 1 vars containing '|'
ok 2 correctly uses custom command to preview directories
ok 3 follows symbolic links
ok 4 displays dir contents without showing ..
ok 5 ~/ is expanded to HOME
ok 6 doesn't change fd's base directory if no slash on current token
ok 7 doesn't prepend ./ if path already starts with /
ok 8 correctly passes fzf_fd_opts when executing fd
ok 9 Outputs right commit (local)
ok 10 correct paths found in output
ok 11 ouputs right command
not ok 12 doesn't overwrite $ when replacing current token with selected variable
  ---
    operator: =
    expected: '$selection'
    actual: ''
    at: ~/hacking/fzf.fish/tests/search_shell_variables/$_in_curr_token.fish:7
  ...
not ok 13 can find a local variable
  ---
    operator: =
    expected: a_local_variable
    actual: ''
    at: ~/hacking/fzf.fish/tests/search_shell_variables/local_var.fish:6
  ...
ok 14 fails if no arguments given

1..14
# pass 12
# fail 2
```

**Comment by teehemkay** [comment]
FWIW, my `$fish_function_path` only has (besides the standard ones) the `vendor_functions.d` directories from `fishtape`, `clownfish` and `fzf.fish`

**Comment by PatrickF1** [comment]
Ah okay, so the part that your installation might be missing is the part where the functions and conf file are installed in the right place and sourced. Fisher usually handles that by putting them in `~/.config/fish/functions` and `~/.config/conf.d`, and I think fish will automatically source files there. You'll need to do that because the tests don't actually use the functions inside the repo. It uses the functions that are installed.

**Comment by jorgebucaran** [comment]
@teehemkay Can you reproduce the problem if installed with Fisher?

**Comment by jorgebucaran** [comment]
Can you reproduce the problem if you install fzf.fish with Fisher?

**Comment by teehemkay** [comment]
Oh, in my testing sandbox I didn't bother setting up the conf dir (the normal `Nixpkgs` install does take care of that), that might be the problem. I'll correct that now. If it still fails, I'll try installing w/ `fisher` :-)

**Comment by teehemkay** [comment]
@jorgebucaran @PatrickF1 it was quicker to test with an `Fisher` install. So I did that first.
Happy to report that the two tests that previously failed, now pass 👍 :
But, now another test is failing :
```
not ok 8 correctly passes fzf_fd_opts when executing fd
  ---
    operator: -n
    expected: a non-zero length string
    actual: ''
    at: ~/hacking/fzf.fish/tests/search_current_dir/pass_custom_fd_opts.fish:10
  ...

**Comment by PatrickF1** [comment]
Can you `echo $fd_captured_opts` after line 8 and give me the output?

**Comment by teehemkay** [comment]
`echo "\$fd_captured_opts='$fd_captured_opts'"`

```
$fd_captured_opts='--color=always --hidden --exclude=.git'
ok 8 correctly passes fzf_fd_opts when executing fd
```

**Comment by PatrickF1** [comment]
I am truly stumped...best course of action I can recommend is to manual test the new feature of using `fzf_fd_opts` to pass custom options to fd and if that works on Nix, then you can assume the plugin works on Nix.

**Comment by teehemkay** [comment]
Oops, looks like I hadn't updated my git repo...

After updating the repo, and with `fzf.fish` installed w/ `Fisher`, all tests pass

Very sorry about the confusion

**Comment by teehemkay** [comment]
So the only remaining issue would be to make sure that `$actual` is enclosed in double quotes:

https://github.com/PatrickF1/fzf.fish/blob/5ce8a51b78abf40468c96c06fd7c896bea7d05c0/tests/search_shell_variables/%24_in_curr_token.fish#L7

`@test "doesn't overwrite \$ when replacing current token with selected variable" "$actual" = "\$selection"`

and

https://github.com/PatrickF1/fzf.fish/blob/5ce8a51b78abf40468c96c06fd7c896bea7d05c0/tests/search_shell_variables/local_var.fish#L6

`@test "can find a local variable" "$actual" = a_local_variable`

Thanks a lot for your support @PatrickF1 and @jorgebucaran, I really appreciate it.
Learned quite a bit about `fish` in the process.

And again, my apologies for the confusion.

**Comment by PatrickF1** [comment]
Good idea @teehemkay. Would you like to PR that in since you already did it?

**Comment by teehemkay** [comment]
> Good idea @teehemkay. Would you like to PR that in since you already did it?

Missed that opportunity. Next time :-)

Thank you.
