### ISSUE TITLE
unknown option: --marker=*

### ISSUE THREAD

**Issue by derVedro** [PatrickF1/fzf.fish#148]
Hey, I wanted to try that all, but if search something with ctrl + f I get a `unknown option: --marker=*` in my shell. If I remove the _marker_ option from here https://github.com/PatrickF1/fzf.fish/blob/20ec3e4eea8e5c9e8c9d156bd9d4270c3b61ba46/conf.d/fzf.fish#L36
it works. May be some ubuntu 20.04 stuff is too outdated?

I use the last fish 3.2.1 from a PPA, but fzf, fd and bat are from vanilla repos:
fd 7.4.0
fzf 0.20.0
bat 0.12.1

**Comment by PatrickF1** [comment]
Great question! Your fzf is from before the --marker flag was introduced. I'd upgrade to at least 0.21 (https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0210). I should add the fzf version as a system requirement in the installatino.
