### ISSUE TITLE
Reverse command search UI is broken

### ISSUE THREAD

**Issue by tuxiqae** [PatrickF1/fzf.fish#166]
**Describe the bug**
When using the `Ctrl`+`R` feature to view (and run) commands from history you can insert text to FZF in order to filter, for some reason it inserts newlines into the text box which breaks the entire UI  

**To Reproduce**
Open reverse command search by clicking on `Ctrl`+`R` and start typing things, it happens almost every time.

**Expected behavior**
I expect to be able to view my history with no issues whatsoever.

**Screenshots**
Terminator:
![image](https://user-images.githubusercontent.com/39622904/120243602-b264ac80-c270-11eb-91b5-b45838b4db11.png)
Alacritty:
![image](https://user-images.githubusercontent.com/39622904/120243545-8ba67600-c270-11eb-9701-c3125da1634b.png)

**Environment**

- Fish: `3.2.2`
- fzf.fish: Not sure, since I update daily using `fisher` I guess that I'm running the newest version - `6.4`
- plugin manager: `fisher 4.3.0`
- terminal: usually `Alacritty`, also found in `Terminator`
- OS: Arch Linux 64-bit, kernel: `5.12.8-lqx1-1-lqx`  
- fzf: `0.27.1`

----
Also found on Apple macOS, using `iTerm2`.

**Additional context**
Anything else?

**Comment by PatrickF1** [comment]
>  it inserts newlines into the text box which breaks the entry UI

I'm afraid I don't understand what you mean by this. Do you mean that as you type into fzf, it creates a new line?

Can you also give you the contents of FZF_DEFAULT_OPTS?

**Comment by tuxiqae** [comment]
**Sometimes** when I type a character into the reverse search it just spawns the cursor somewhere else instead of where it should be:
![image](https://user-images.githubusercontent.com/39622904/120274128-152d6680-c2b8-11eb-8f2a-021a083382ff.png)
I wrote `a` and instead of pointing to the space after the a - it just decided to point to the line below..
Added a couple of more letters and now the cursor is here:
![image](https://user-images.githubusercontent.com/39622904/120274270-45750500-c2b8-11eb-9433-dc7adc2d67bb.png)


FZF_DEFAULT_OPTS = `--cycle --layout=reverse --border --height=90% --preview-window=wrap --marker="*"`

**Comment by PatrickF1** [comment]
Oh wow, I can repro this on my set up as well. And I noticed I can't repro it for any other feature. Thanks for reporting this! I'll look into it more tomorrow!!

CC: @kidonng whom I know loves a good fishy mystery to solve

**Comment by PatrickF1** [comment]
Oh I know what might be going on. This has to do with the preview-window. fzf may have a bug rendering it when it's different sizes. I noticed that the bug is triggered whenever I select very long, multi-line commands.

**Comment by tuxiqae** [comment]
I'm so happy of how proactive you are, I was dealing with this bug for quite the while before reporting it, and it was driving me nuts!

**Comment by PatrickF1** [comment]
Of course! This plugin is my baby and I want it to serve all my users well :) And I'm sorry it was driving you crazy. Anyway, unfortunately, this is not something I can fix b/c it rests with fzf, of which I am not a contributor to. I'll do some more research and decide on an option. In the meantime, I suggest using setting `fzf_history_opts` to remove the preview window to fix it.

**Comment by PatrickF1** [comment]
Btw, I would really appreciate if you could star this repo as a token of your appreciation. 500 stars is my dream 😜

**Comment by tuxiqae** [comment]
> Btw, I would really appreciate if you could star this repo as a token of your appreciation. 500 stars is my dream stuck_out_tongue_winking_eye

I tend to star all the repos I use, weird that I missed this one. Done :)

**Comment by tuxiqae** [comment]
> Of course! This plugin is my baby and I want it to serve all my users well :) And I'm sorry it was driving you crazy. Anyway, unfortunately, this is not something I can fix b/c it rests with fzf, of which I am not a contributor to. I'll do some more research and decide on an option. In the meantime, I suggest using setting `fzf_history_opts` to remove the preview window to fix it.

Maybe opening an issue on `fzf`s repository will be best, would you mind doing that? (since you have all the technical details regarding the issue)

**Comment by PatrickF1** [comment]
> I tend to star all the repos I use, weird that I missed this one. Done :)

Thank you! Appreciate your support :)

> Maybe opening an issue on fzfs repository will be best, would you mind doing that? (since you have all the technical details regarding the issue)

Yup, Junegunne is _so_ responsive. He's incredible. I've gone opened up many issues there already and he always gets back to me within 2 days with a smart and patient response. What a man and what a project to built my project on top of. Of course I'm going to respect him by taking the time to write a great issue to save him time. Will link it here when I get to this tomorrow.

**Comment by tuxiqae** [comment]
Thanks a bunch @PatrickF1! You're great help!

**Comment by PatrickF1** [comment]
https://github.com/junegunn/fzf/issues/2512

**Comment by kidonng** [comment]
I've encountered this bug, obviously it's an issue with fzf which is not specific to this plugin. My answer is to delete the offending history entries, since they tend to be too long and specific to be useful in the future.

**Comment by PatrickF1** [comment]
Closing this now since I'm 90% certain 0.27.2 fixes this. I will update the readme to require 0.27.2.
Thank you again for filing this issue Sagi!
