### ISSUE TITLE
config.fish is called by fzf X times

### ISSUE THREAD

**Issue by raven2cz** [PatrickF1/fzf.fish#181]
## Describe the bug

I found some potential error. I expect that `config.fish` has to be called just one time when fish is launched. 

For example I "wrongly" inserted ascii art function to the last line of config.fish:

`colorscript random` - script created by DT, gitlab resource.  

I started fzf history search and the colorscript is shown instead of command preview. I started search file, and color script is shown instead of preview of file. 

Maybe it is some behavior of fish, but there has to be explanation why the lines of config.fish are call if your preview is shown. If the config.fish is called for each preview, it is very bad. 

## Steps to Reproduce

Download DT gitlab colorscript, place last row `coloscript random` to config.fish and test fzf.

## Screenshots

![fish-error](https://user-images.githubusercontent.com/20504243/123534188-8cb9ae80-d71b-11eb-936d-7c6988968699.png)

## Environment

Versions installed:

- fish, version 3.2.2
- fzf.fish: 7.1
- plugin manager: 4.3.0
- terminal: alacritty
- OS: arch

**Comment by kidonng** [comment]
https://github.com/fish-shell/fish-shell/pull/7796#discussion_r598227953

**Comment by PatrickF1** [comment]
Yup, the way fzf previews work is they spawn a new instance of $SHELL. And whenever a new shell starts up, it loads its config files.

**Comment by raven2cz** [comment]
Thanks for info.

So, it is just calling of `config.fish` for this preview instance, or some allocation of all next functions in the fish directory? Because I have a lot of functions defined in the `config.fish`. For example if I moved it to the function part, if it will be more efficient. 

I don't use interactive block, but I used

```
# Fish greetings when the terminal is shown up in interactive mode
function fish_greeting
    colorscript random
end
```

Is it correct or there is some hidden problem?

Just small question before closing this issue. The preview is using bat, is there some possibility to show images and pdf files content? Can you give me some trick to it, thanks again.

**Comment by PatrickF1** [comment]
> So, it is just calling of config.fish for this preview instance, or some allocation of all next functions in the fish directory?

fzf preview loads a new shell. Whenever a new shell starts up, it loads config.fish.

> Because I have a lot of functions defined in the config.fish. For example if I moved it to the function part, if it will be more efficient.

I'd recommend moving your functions out of config.fish and defining them as autoloaded functions.

> Is it correct or there is some hidden problem?

Seems fine to me.

> The preview is using bat, is there some possibility to show images and pdf files content?

Check out https://github.com/PatrickF1/fzf.fish/wiki/Cookbook#how-can-i-customize-file-previews-based-on-the-file-type.


As a token of appreciation, I'd really appreciate if you starred this repo. I'm trying to hit 500 stars. Thanks for considering it.
