### ISSUE TITLE
fzf results contain bind commands

### ISSUE THREAD

**Issue by 037g** [PatrickF1/fzf.fish#183]
## Describe the bug
adding `fzf_configure_bindings --directory=\cf` to `config.fish` adds additional lines of text to all fzf results:

`bind --preset \\cv fish_clipboard_paste`
`bind --preset -M insert \\cv fish_clipboard_paste`

## Screenshots
<img width="1782" alt="example1" src="https://user-images.githubusercontent.com/27838675/124343007-6621ca80-db96-11eb-9269-2bb439fd99f9.png">

<img width="490" alt="example2" src="https://user-images.githubusercontent.com/27838675/124343015-6d48d880-db96-11eb-826a-6c8d834a3a62.png">

![image](https://user-images.githubusercontent.com/27838675/124343039-89e51080-db96-11eb-8a2d-e5a140dab38e.png)

## Environment

- [x ] I have made sure my CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)

Versions installed:

- Fish: [e.g. 3.2.2] Fish Shell 3.3.0
- fzf.fish: [e.g. 7.0] check
- plugin manager: [e.g. fisher 4.3.0] check
- terminal: [e.g. iTerm] ITerm 3.48
- OS: [e.g. macOS 10.15.7] macOS BigSur 11.4

## Additional context

Anything else?

**Comment by PatrickF1** [comment]
Hmm that is very mysterious indeed. I double checked the code for `fzf_configure_bindings` and don't see any place where such output would escape.

1. Does that output also show up when you first start a new fish shell?
2. can you append `2>/dev/null` to your invocation of fzf_configure_bindings in config.fish and see if it still happens?

**Comment by kidonng** [comment]
These lines only appear in `__fish_shared_key_bindings`. Try remove `fish_vi_key_bindings` from your Fish config and see if the results are different.

**Comment by syphar** [comment]
I also started seeing this message after some upgrades, fish and this plugin is up-to-date. 

To answer some of the questions: 

> can you append 2>/dev/null to your invocation of fzf_configure_bindings in config.fish and see if it still happens?

the output when starting the shell still appears. 

> These lines only appear in __fish_shared_key_bindings. Try remove fish_vi_key_bindings from your Fish config and see if the results are different.

now I'm seeing: 
```
bind: No binding found for sequence '\cv'
bind: No binding found for sequence '\cv'
bind: No binding found for sequence '\cv'
bind: No binding found for sequence '\cv'
```



> can you give me the output of `bind --user` please? (and also double check that they are what you expect)

here is my output (with some custom bindings): 
```
bind -M insert \cp vv
bind -M insert \ct ftags
bind -M insert \ce insert_heroku_app
bind -M insert \co cdp
bind -M insert \cq fg_
bind -M insert \cc kill-whole-line repaint
bind \cf _fzf_search_directory
bind \e\cl _fzf_search_git_log
bind \e\cs _fzf_search_git_status
bind \cr _fzf_search_history
bind \cv '_fzf_search_variables (set --show | psub) (set --names | psub)'
bind -M insert \cf _fzf_search_directory
bind -M insert \e\cl _fzf_search_git_log
bind -M insert \e\cs _fzf_search_git_status
bind -M insert \cr _fzf_search_history
bind -M insert \cv '_fzf_search_variables (set --show | psub) (set --names | psub)'
```

Seeing this, could this be a conflict between `fzf_configure_bindings` and `fish_vi_key_bindings` both trying to bind `\cv`?

**Comment by kidonng** [comment]
Try running `set -U fish_key_bindings fish_vi_key_bindings` once instead of executing `fish_vi_key_bindings` in your `config.fish`.

**Comment by syphar** [comment]
> Try running `set -U fish_key_bindings fish_vi_key_bindings` once instead of executing `fish_vi_key_bindings` in your `config.fish`.

Then I'm seeing `bind: No binding found for sequence '\cv'`, except when I also remove `fzf_configure_bindings --directory=\cf`.

**Comment by kidonng** [comment]
At you using tide?

**Comment by syphar** [comment]
> At you using tide or anything that runs in background?

yep, tide 

> Put `status -i || exit` before your key bindings and try again.

no error then. Interesting is that I still have my mappings.

**Comment by 037g** [comment]
I see a pull request to fix this. Thank you.

I am not using tide. Just [starship.rs](https://starship.rs).

@PatrickF1 

1. Does that output also show up when you first start a new fish shell? `no, only when some command calls the interactive tool`

2. can you append 2>/dev/null to your invocation of fzf_configure_bindings in config.fish and see if it still happens?
`Did not make a difference`

3. can you give me the output of bind --user please? (and also double check that they are what you expect)

Output of:
```shell
❯ bind --user
bind -M insert '(' _pisces_insert_left\ \\\(\ \\\)
bind -M insert ')' _pisces_insert_right\ \\\)
bind -M insert '[' _pisces_insert_left\ \\\[\ \\\]
bind -M insert ']' _pisces_insert_right\ \\\]
bind -M insert '{' _pisces_insert_left\ \\\{\ \\\}
bind -M insert '}' _pisces_insert_right\ \\\}
bind -M insert '"' _pisces_insert_identical\ \\\"
bind -M insert \' _pisces_insert_identical\ \\\'
bind -M insert -k backspace _pisces_backspace
bind -M insert \x7f _pisces_backspace
bind -M insert \t _pisces_complete
bind -M insert . _puffer_fish_expand_dots
bind -M insert ! _puffer_fish_expand_bang
bind \cf _fzf_search_directory
bind \e\cl _fzf_search_git_log
bind \e\cs _fzf_search_git_status
bind \cr _fzf_search_history
bind \cv '_fzf_search_variables (set --show | psub) (set --names | psub)'
bind -M insert \cf _fzf_search_directory
bind -M insert \e\cl _fzf_search_git_log
bind -M insert \e\cs _fzf_search_git_status
bind -M insert \cr _fzf_search_history
bind -M insert \cv '_fzf_search_variables (set --show | psub) (set --names | psub)'
```


Other fish shell plugins.
``` shell
omf l
Plugins
aws		fish-spec	omf

fisher list
jorgebucaran/fisher
edc/bass
laughedelic/pisces
jethrokuan/z
evanlucas/fish-kubectl-completions
markcial/upto
nickeb96/puffer-fish
h-matsuo/fish-color-scheme-switcher
PatrickF1/fzf.fish
patrickf1/colored_man_pages.fish
```

**Comment by 037g** [comment]
> These lines only appear in `__fish_shared_key_bindings`. Try remove `fish_vi_key_bindings` from your Fish config and see if the results are different.
> 
> Also, are you using [tide](https://github.com/IlanCosman/tide)?

Removing vi bindings fixes the problem.

**Comment by Kabouik** [comment]
I'm observing the same with no bindings set in my Fish config:

```
# Remove greeting
set fish_greeting

# fzf.fish keybindings (https://github.com/PatrickF1/fzf.fish)
set fzf_fd_opts --hidden --exclude=.git
fzf_configure_bindings --directory=\cF --git_status=\cS --git_log=\cG --history=\cR --variables=\cV
```

![Screenshot_20210711_001](https://user-images.githubusercontent.com/7107523/125193677-f7a3d300-e24d-11eb-832c-79c7d137fa55.png)
(Excuse the dpi, it's from a 6" phone.)

However, I'm not using Fish >3.2.0 yet because the package on Debian Sid currently is 3.1.3 only, don't know if this specific problem is related. I'm realizing as I post this message that the config to show hidden directories/files with `<c-f>` doesn't work, but this may indeed be due to my version of Fish.

**Comment by kidonng** [comment]
@Kabouik maybe use lowercase i.e. `\cf` instead of `\cF`.

**Comment by Kabouik** [comment]
That was actually what I did initially, and just tried with upper case later when I saw the issue. It seemed to make no difference unfortunately. It's fairly minor anyway, but just wanted to mention that the issue shows up for me too even though I did not set vi keybindings in my fish config.

**Comment by PatrickF1** [comment]
Hi @Kabouik! Sorry for the late reply. Can you try adding `> /dev/null 2>&1` to your `fzf_configure_bindings` command and see if it still happens? It'll help me isolate the problem.

**Comment by PatrickF1** [comment]
Ok actually, you don't need to do that. I thought about it some more and I know what's wrong. It's because you are passing the flag `--variables=\cV`, which uses `$_fzf_search_vars_command`. But `_fzf_search_vars_command` is no longer being set in `conf.d/fzf.fish` if the shell is interactive. Turns out @kidonng already realized this was a bug a while ago.

**Comment by PatrickF1** [comment]
Sorry for everyone who had this issue...now I know why fzf.fish lost 5+ stars in the past 2 weeks :(

**Comment by Kabouik** [comment]
Awesome, that seems to work, thanks @PatrickF1. And fzf.fish is great, no worries, I starred it and started recommending it right after I learnt about it!

**Comment by PatrickF1** [comment]
Thanks @Kabouik!
