### ISSUE TITLE
weird output with fish-apple-touchbar & iterm2

### ISSUE THREAD

**Issue by fredericrous** [PatrickF1/fzf.fish#184]
## Describe the bug
When I use fzf.fish in conjunction with fish-apple-touchbar, I am getting extra lines containing "1337;SetKeyLabel=" shown on the attached screenshot

## Steps to Reproduce

1. fisher install rodrigobdz/fish-apple-touchbar
2. fisher install PatrickF1/fzf.fish
3. Ctrl+R

## Screenshots
![image](https://user-images.githubusercontent.com/702227/124274144-ceda5a00-db38-11eb-9ce9-3e05c3f3bbc5.png)

## Environment

- [x] I have made sure my CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)

Versions installed:

- Fish: 3.3.0
- fzf.fish: 7.1
- plugin manager: 4.3.0
- iTerm2: 3.4.6
- macOS Big Sur 11.4

## Additional context

I configured fish-apple-touchbar 1.0.0 like so:

```sh
cat  ~/.config/fish/conf.d/touchbar.fish
__fish_apple_touchbar_bind_key_custom 1 '👈' 'prevd' '-s'
__fish_apple_touchbar_bind_key_custom 2 '🗄 jump' 'cdh' '-s'
```
https://github.com/fredericrous/dotfiles/blob/main/private_dot_config/private_fish/conf.d/touchbar.fish
https://github.com/fredericrous/dotfiles/blob/main/private_dot_config/private_fish/functions/__fish_apple_touchbar_bind_key_custom.fish

```sh
fzf_configure_bindings --directory=\cf --git_log=\cg --git_status=\cs
```
https://github.com/fredericrous/dotfiles/blob/master/private_dot_config/private_fish/config.fish#L38

This issue might be related to https://github.com/PatrickF1/fzf.fish/issues/183, but the extra lines appear at a different spot.

My exact config for fish is there https://github.com/fredericrous/dotfiles/tree/main/private_dot_config/private_fish
The extra characters 1337 are apparently issued by iterm2
The issue does not seem to come from fish-apple-touchbar plugin https://github.com/rodrigobdz/fish-apple-touchbar/issues/13

**Comment by PatrickF1** [comment]
Sorry about the bug! Can you add 2>/dev/null to fzf_configure_bindings and see if anything changes?

**Comment by fredericrous** [comment]
no change

**Comment by PatrickF1** [comment]
>  Maybe we could just deactivate the preview by setting an environment variable for example?

Sure check this out https://github.com/PatrickF1/fzf.fish/wiki/Cookbook#how-can-i-disable-the-fzf-preview-pane-for-a-particular-command.

Thanks for giving me such detailed screenshots and description of your set up. It really helps with debugging! 💯
Anyway, are you using Tmux? I suspect that https://github.com/rodrigobdz/fish-apple-touchbar/blob/main/functions/__fish_apple_touchbar_print_key.fish#L6 is causing the output. In which case your touchbar config might have a bug in it. I'm not too familiar with the touchbar code so can't say right now...

**Comment by fredericrous** [comment]
I suspected the same, tried disabling the print_key function, but it appears that this function is essential for the custom buttons to appear in the touchbar.
Thanks for directing me to this part of the doc, I hadn't noticed `fzf_git_log_opts`. It feels better than overriding the function `_fzf_search_history` 😅

**Comment by PatrickF1** [comment]
I am so confused....thanks for reporting back though! Are you saying this is more of an fzf bug?

**Comment by fredericrous** [comment]
I don't know for sure if it's a bug with fzf but this characters should in theory be "removed" by iTerm2.. I written an issue report and was ready to send it to iTerm2 bug tracker, when I found the workaround. Because I don't understand why this workaround is working  and I already spend too much time on that, I kinda gave up and didn't send the issue

**Comment by kidonng** [comment]
This is not a bug with either fzf.fish or fish-apple-touchbar. It's because you are calling `__fish_apple_touchbar_bind_key_custom` in `conf.d/touchbar.fish`, which in turn calls `__fish_apple_touchbar_print_key` and output those escape codes. conf.d scripts will be sourced even in non-interactive sessions, and that's where fzf's preview window runs.

It is very likely that you have guard your config with `status -i || exit` or something similiar when you put it in `config.fish`.

**Comment by PatrickF1** [comment]
Thank you for debugging this @kidonng !

**Comment by fredericrous** [comment]
That explains why I had no issue when I put that in my config.fish. You're totally right @kidonng, I indeed ended up putting the lines `__fish_apple_touchbar_bind_key_custom` at the bottom, behind a [status is-interactive || exit](https://github.com/fredericrous/dotfiles/blob/ba69aa6dada00af333846d0860fee34d98c80468/private_dot_config/private_fish/config.fish#L32)... I'll use this check in `touchbar.fish` instead, thank you.
