### ISSUE TITLE
Argument is not a number: '' - if test "$FZF_DISABLE_KEYBINDINGS" -ne 1

### ISSUE THREAD

**Issue by pbadenski** [PatrickF1/fzf.fish#192]
## Describe the bug

```
Argument is not a number: ''
~/.config/fish/conf.d/fzf_key_bindings.fish (line 1): 
if test "$FZF_DISABLE_KEYBINDINGS" -ne 1
   ^
from sourcing file ~/.config/fish/conf.d/fzf_key_bindings.fish
	called on line 253 of file /usr/local/Cellar/fish/3.3.1/share/fish/config.fish
from sourcing file /usr/local/Cellar/fish/3.3.1/share/fish/config.fish
	called during startup
```

## Steps to Reproduce

Failing right after the installation.

## Environment

- [x] I have made sure my CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)

Versions installed:

- Fish: 3.3.1
- fzf.fish: 7.2
- plugin manager: 4.3.0
- terminal: MacOS Terminal
- OS: 10.15.7

**Comment by PatrickF1** [comment]
Hi @pbadenski ! It seems you are sourcing `~/.config/fish/conf.d/fzf_key_bindings.fish`. That file doesn't exist anymore as of fish 7.0. Why are you sourcing it and why does it still exist on your filesystem?
This might be helpful if you didn't get to read it. https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides#v7

**Comment by pbadenski** [comment]
Thanks!

Long story... I uninstalled  `jethrokuan/fzf`... But I had a botched configuration after upgrading fish a while back. Thought I cleaned it all up, but had this one file that was dangling. I just deleted it manually, reinstalled fzf.fish and it's fine now!

**Comment by PatrickF1** [comment]
You're welcome. Glad to hear it's resolved!
