### ISSUE TITLE
Binding to open in Neovim not working

### ISSUE THREAD

**Issue by euglevi** [PatrickF1/fzf.fish#203]
## Describe the bug

First of all, thank you for the great plugin! I have quite a minimal config in my config.fish:

```
fzf_configure_bindings --directory=\cx
set fzf_fd_opts --hidden -E .git -E .virtualenvs -E .cargo -E .cache -E .fonts -E .steam -E .local/lib -E .local/etc -E .local/state -E .rustup -E .themes -E dotfiles
set fzf_dir_opts --bind "ctrl-v:execute(nvim {})+abort,tab:down,shift-tab:up,ctrl-a:toggle+down" --border=none
```
Everything seems to be working except for the ctrl-v binding. Whenever I try it, I get the following:

![28_10_21_10_00_01](https://user-images.githubusercontent.com/58224469/139213350-0400cf5d-cc16-4c2d-a671-ee9d675f3c2a.png)

I can get out of this screen by pressing \cc.

When I try the same with `ls | fzf --bind "ctrl-v:execute(nvim {})"`, everything works as expected.

## Environment

Versions installed:

- Fish: 3.3.1
- fzf.fish: last one
- plugin manager: fisher 4.3.0
- terminal: kitty
- OS: Ubuntu Hirsute

**Comment by euglevi** [comment]
I tried but with no luck. If I substitute nvim with another app, like libreoffice, the keybinding works. So I suspect this issue has not to do with strings as much as with terminals. I am sorry I cannot be of further help as I know very little fish programming.

**Comment by PatrickF1** [comment]
Got it. I will try to find some time to look into it. Thanks for your patience!

**Comment by PatrickF1** [comment]
Ok I think I figured it out. The reason executing nvim doesn't work is because fzf is executed in a command substitution.
To see this for yourself, see that
```
ls | fzf --bind "ctrl-v:execute(nvim {})"
```
works but this does not
```
set v (ls | fzf --bind "ctrl-v:execute(nvim {})")
```
Let me find a way around this. This is a pretty limiting :(

**Comment by PatrickF1** [comment]
Aw man, I don't think there's a way around it. I tried using
```
ls | fzf --bind "ctrl-v:execute(nvim {})" | read v
```
but had the same problem. I'll ask the maintainers for fish-shell for ideas or a patch, but it looks grim. Sorry. I will need to remove the idea of using `--bind` to do cool things from the readme.

**Comment by euglevi** [comment]
I could indeed replicate your debug. By the way, it is the same also with the keybindings provided by the official fzf page, so this is clearly not an issue related to the plugin itself. Let us see if maintainers of fish-shell have ideas. Notice that this is not related to Neovim only because the same problem arises also with Vim or with Nano so it must have to do with stdin, as you were suggesting.  

Thank you very much for your time and effort!

**Comment by euglevi** [comment]
Ok I think I solved this. Try this:

`set v (ls | fzf --bind "ctrl-v:execute(nvim {} &> /dev/tty)")`

You need to redirect both input and output to tty.

**Comment by PatrickF1** [comment]
Thanks @euglevi! I will add this to the troubleshooting
