### ISSUE TITLE
ctrl + v it's not work,  ctrl + alt + v it work !

### ISSUE THREAD

**Issue by xBLACKICEx** [PatrickF1/fzf.fish#210]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)

## Describe the bug
`ctrl` + `v` it's not work,

`ctrl`+`alt`+`v` it work !

Is this a typo on README.md?

## Environment

Versions installed:

- Fish: 3.3.1
- fzf.fish: 7.3
- plugin manager: fisher 4.3.0
- terminal: Windows terminal
- OS: windows 11 WSL Arch Linux

**Comment by PatrickF1** [comment]
Hi! This might be a windows bug. I never test on windows. But just to make sure, can you
1. double check your config.fish for an invocation of `fzf_configure_bindings` to make sure you're not already using custom keybindings
2. if not, try invoking `fzf_configure_bindings` and then try Ctrl+V again to see if it works

**Comment by xBLACKICEx** [comment]
@PatrickF1 
> Hi! This might be a windows bug. I never test on windows. But just to make sure, can you
> 
> 1. double check your config.fish for an invocation of `fzf_configure_bindings` to make sure you're not already using custom keybindings
> 2. if not, try invoking `fzf_configure_bindings` and then try Ctrl+V again to see if it works

well i re install fish, and fzf, the result is the same. `ctrl`+`v` it not work, than later I found out that this shortcut key is preset in *windows terminal*.
![image](https://user-images.githubusercontent.com/51036094/143777145-020beca9-dfa9-49d2-aa16-1cbb62b756ff.png)
But that doesn't explain why ctrl+alt+v works. So strange
![wt-fzf fish-cv-bug](https://user-images.githubusercontent.com/51036094/143777839-93b2bfbc-b6ef-4187-a09f-aa8d44304e5d.gif)
.

**Comment by PatrickF1** [comment]
I see. But can you run
```
grep fzf .config/fish/config.fish
```
(dunno where Windows installs config.fish, but update that path if it is installed elsewhere)
I just want to make sure you're not already invoking `fzf_configure_bindings` in your config.fish

**Comment by xBLACKICEx** [comment]
![image](https://user-images.githubusercontent.com/51036094/143784328-6686e615-0db4-48ec-8f75-8728c423a26b.png)
well look like is clean

**Comment by xBLACKICEx** [comment]
@PatrickF1
![image](https://user-images.githubusercontent.com/51036094/143784701-23ccd7f0-8700-4178-aad2-d7ad366bf84f.png)

I had the right idea I found the windows terminal setting.json(`ctrl`+`,` and click **Open JSON file**), after comment out `ctrl`+`v`, then fzf.fish `ctrl`+`v` works.😊

**Comment by PatrickF1** [comment]
Yay glad we resolved this! Thanks for opening this issue
