### ISSUE TITLE
unable to bind \cd

### ISSUE THREAD

**Issue by zim0369** [PatrickF1/fzf.fish#223]
```fish
fzf_configure_bindings --directory=\cd
```
won't work but, something like:
```fish
fzf_configure_bindings --directory=\ck
```
works fine

**Comment by zim0369** [comment]
> `fzf_configure_bindings --directory=\cd` works just fine for me. Can you check your terminal settings to make sure it's not being intercepted by your terminal before that key sequence makes it to fish?
> 
> If you don't find anything, can you confirm that `bind \cd ls` works?

Oh yes. It was mapped to halfpagedown. I should've noticed.

I'm using alacritty terminal. Is there a way to use \cd for halfpagescrolldown in normal mode and for fzf in insert mode?

**Comment by PatrickF1** [comment]
Yes, use bind --mode https://fishshell.com/docs/current/cmds/bind.html. bind it for fzf in insert mode only in your config.fish
