### ISSUE TITLE
file completion not working

### ISSUE THREAD

**Issue by asegarra** [PatrickF1/fzf.fish#244]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [ ] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up

## Describe the bug

Default  CTRL + ALT + F open fzf but without any files to search. 
Went through the troubleshooting page and nothing

## Steps to reproduce

stock fish and this plugin

## Environment

Versions installed:

- fish: 3.4.1
- fzf: 0.30.0
- fzf.fish: latest
- fd: 8.2.1
- bat: 0.18.3
- terminal: foot
- OS: fedora 36

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set?

nothing has been customized

**Comment by PatrickF1** [comment]
Hi, sorry to hear that. So you 
- got no error message and 
- you are sure you're in a directory with files
- your command line was empty?

**Comment by asegarra** [comment]
Hi, yes to all. No clue what I'm doing wrong, everything else appears to be working.

**Comment by PatrickF1** [comment]
Can you try 
- running fd in that directory and checking if it's also an empty output?
- running search directory in other directories?

If all else fails, you can try modifying _fzf_search_directory and printing/echoing the different variables that get set.

**Comment by ajitid** [comment]
@asegarra It could be that dependencies that this plugins rely on have an outdated version on your machine. See [min. version deps. list here](https://github.com/PatrickF1/fzf.fish#installation) and ensure `fd --version` >= 8.4.0. Otherwise, grab the latest version from their releases page.

I faced the same problem, and it got fixed by using the recent version of fd-find

**Comment by asegarra** [comment]
Thanks @ajitid that was it! Thanks @PatrickF1 for the help and the very useful  package.
