### ISSUE TITLE
multi select for history (ctrl+r) puts timestamps in front of all but the first command

### ISSUE THREAD

**Issue by acegallagher** [PatrickF1/fzf.fish#251]
## Before proceeding...

- [ X] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [ X] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [ X] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up

## Describe the bug

ctrl+r and then tab to select multiple entries puts the timestamp in front of the entries, like:

![selecting commands](https://user-images.githubusercontent.com/25115064/182724823-ef06460d-a986-4516-afca-8040edc535e0.jpeg)
![after selected](https://user-images.githubusercontent.com/25115064/182724825-d9af41cc-6eac-48b2-9643-86e89c3274ba.jpeg)

I imagine this is repeatable behavior for the package, but I'm happy to help debug of course if it's somehow only my setup. I'm also looking at the code now and trying to see if I could submit a pull request.

## Environment

Versions installed:
bat 0.21.0 (405e5f74)
fd 8.4.0
fzf 0.31.0 (a0ef898)
fish, version 3.4.1

- terminal: konsole
- OS: Linux 5.18.14

Thanks much for putting together something so well thought out.

**Comment by acegallagher** [comment]
Ah yeah, I have a pull request, just needed to change a few lines. Here is the code snippet:

`        set -U commands_selected # empty list to loop over selected commands, in case multiple                                        
        for c in (string split \n $command_with_ts)                                                                                   
            set --append commands_selected (string split --max 1 " │ " $c)[2]                                                         
        end                                                                                                                           
        commandline --replace -- $commands_selected  `

Incoming!

**Comment by PatrickF1** [comment]
Hi @acegallagher, the search history feature does not multi-select by default, so you must've configured it to be multi-selectable. What's your use case for selecting multiple commands?
