### ISSUE TITLE
Files with spaces or special characters

### ISSUE THREAD

**Issue by raphael-small** [PatrickF1/fzf.fish#265]
Hi,

Thanks for fzf.fish, it works great, though on file completion escaping backshlashes are not added which leads to no working commands
eg. cp machin\ truc\ bidule ~ becomes cp machin truc bidule ~

Thanks

**Comment by PatrickF1** [comment]
very odd I am not able to reproduce the bug. Can you follow the issue reporting template so I have more info to repro it?
https://github.com/PatrickF1/fzf.fish/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by PatrickF1** [comment]
Hi @raphael-small , one possibility is that you are using a different plugin. fzf.fish often gets confused with the fish integration installed by fzf.

Closing this for now. Feel free to re-comment if you still have problems. https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish

**Comment by raphael-small** [comment]
Hi,

thanks for your reply, it's totally possible, I'll investigate
have a nice day

**Comment by raphael-small** [comment]
It was indeed the fzf integration that had problems
Sorry for the noise
