### ISSUE TITLE
Search history doesn't respect chronological order

### ISSUE THREAD

**Issue by jjant** [PatrickF1/fzf.fish#272]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [x] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up

## Describe the bug

Search history should (imho) respect chronological order of commands, but it doesn't. See:

![image](https://user-images.githubusercontent.com/15112080/197335580-4b5c05c9-cea3-424a-93d9-3f6715ac4c15.png)
![image](https://user-images.githubusercontent.com/15112080/197335588-a3be74cb-739b-4d64-af97-38190260f4a7.png)

## Steps to reproduce

Type a partial command search with shorter matches (`conf` above) that happened earlier in time.

## Environment

Versions installed:

- Fish: `3.5.1`
- fzf.fish: `8.3`
- terminal: Alacritty
- OS: `macOS 12.6`

**Comment by PatrickF1** [comment]
Good point. I also prefer chronological ordering but a lot of people prefer best match first. You can turn off sorting by relevance via `--no-sort` https://github.com/junegunn/fzf/issues/1189. I will add this to the cookbook.

**Comment by jjant** [comment]
Thank you!
