### ISSUE TITLE
Git log showing raw GPG output as commits 

### ISSUE THREAD

**Issue by c4tich** [PatrickF1/fzf.fish#286]
## Before proceeding...

- [X] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [X] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [X] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up

## Describe the bug

If you happen to have GPG signed commits and your repo or global git configuration showw GPG signatures by default (setting `showSignature = true` on the repo or the global `.gitconfig`) , the signatures appear on the git log as entries that parse with errors. An example is this very repo, see the capture below:

![image](https://user-images.githubusercontent.com/6342842/210444895-489ef67c-c491-471f-bdc1-c7de37403128.png)

with my global `.gitconfig` being like this:
```bash
[user]
        signingKey = xxxx
        name = xxx
        email = xxx
[commit]
        gpgSign = true
[core]
        editor = vim
[gpg]
        program = gpg
[log]
        showSignature = true 
[init]
        defaultBranch = master
```

If you force git to not show GPG signatures (by commenting showSignature = true), this of course disappears

![image](https://user-images.githubusercontent.com/6342842/210445439-d5d88928-efce-4c0a-ad7b-05702e295141.png)

but I see this suboptimal since it hides the signature information

## Steps to reproduce
Use git log on a repo with gpg-signed commits 

## Environment

Versions installed:

- Fish: 3.5.1
- fzf.fish: 9.5
- terminal: Konsole
- OS: Arch Linux

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set?
None 

## Additional context
None

**Comment by c4tich** [comment]
I opened https://github.com/PatrickF1/fzf.fish/pull/287 that adds a new flag to indicate the status of the signature, as per [`git log`'s `%G?`](https://git-scm.com/docs/git-log#Documentation/git-log.txt-emGem) flag. The values are:

> show "G" for a good (valid) signature, "B" for a bad signature, "U" for a good signature with unknown validity, "X" for a good signature that has expired, "Y" for a good signature made by an expired key, "R" for a good signature made by a revoked key, "E" if the signature cannot be checked (e.g. missing key) and "N" for no signature

For "E" (can't verify signature) it looks like this:
![before](https://user-images.githubusercontent.com/6342842/210451746-d51a048c-b430-47e6-b6c2-b3d5d44d8096.png)

and for "G" (good valid signature) it looks like this:
![after](https://user-images.githubusercontent.com/6342842/210451779-1e564c12-5d4c-432c-b787-30c0088e6774.png)

and I can't really test the other use cases 😅

**Comment by PatrickF1** [comment]
I know this is slightly tangential to the bug, but I want to make sure I understand exactly what is happening and how GPG integrates with git before I fix the bug. When the error message says `gpg: Can't check signature: No public key`, is that because it found a signed commit but can't verify the signature because your gpg config doesn't have the public key used to sign that signature?

**Comment by c4tich** [comment]
> it found a signed commit but can't verify the signature because your gpg config doesn't have the public key used to sign that signature

Exactly this. The user's keyring does not contain a public key paired to the private key used to generate the signature
