### ISSUE TITLE
Error which appears in every preview: "can't find session"

### ISSUE THREAD

**Issue by DakEnviy** [PatrickF1/fzf.fish#289]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I have read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [x] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up

## Describe the bug

**When tmux is running:**

Error message appears in every preview. Error message format: `can't find session: <some_number>`

![Снимок экрана от 2023-01-11 12-13-31](https://user-images.githubusercontent.com/6522772/211765579-4ce5e254-c6ef-42da-9896-f196783e45ed.png)
![Снимок экрана от 2023-01-11 12-14-24](https://user-images.githubusercontent.com/6522772/211765772-96d7b805-b0af-4df6-acf8-8930f8d5950a.png)

**Without tmux:**

Error message appears in every preview. Error message: `no server running on /tmp/tmux-1000/default`

![Снимок экрана от 2023-01-11 12-17-47](https://user-images.githubusercontent.com/6522772/211766531-38b74787-652a-42bb-8362-d78412756f1b.png)

## Steps to reproduce

Just run any command with preview.

## Environment

Versions installed:

- Fish: 3.4.0
- fzf.fish: commit `5ecaeb65ff892547c34f6a9a33761acabff39261`
- terminal: BlackBox
- OS: Gentoo Linux 6.1.1

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set?

```
set fzf_preview_dir_cmd exa -la --group-directories-first --icons --no-permissions --no-user --no-filesize --no-time
set fzf_fd_opts --hidden --exclude=.git
```

**Comment by PatrickF1** [comment]
Does that error happen if you spawn a new fish shell. e.g. `fish` while in a fish session?

**Comment by PatrickF1** [comment]
This might be relevant. https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting#error-text-being-printed-on-topbottom-of-fzf-previews

**Comment by DakEnviy** [comment]
Yeah, you are right. Thank you for your help! I have this configuration for tmux:

```
alias tn 'tmux new-session -s $fish_pid'
trap 'tmux kill-session -t $fish_pid' EXIT
```

The problem was this. My fix is:

```
alias tn 'tmux new-session -s $fish_pid'

if status is-interactive
    trap 'tmux kill-session -t $fish_pid' EXIT
end
```

Do you think that is good enough?

**Comment by PatrickF1** [comment]
Yes, that's perfect! In my own dotfiles (https://github.com/PatrickF1/dotfiles/blob/main/.config/fish/config.fish#L28), I do `status is-interactive || exit` and put everything for interactive use below it.
