### ISSUE TITLE
Unknown command set -f file_paths_selected ($fd_cmd 2>/dev/null | _fzf_wrapper $fzf_arguments)

### ISSUE THREAD

**Issue by Drew-Daniels** [PatrickF1/fzf.fish#304]
## Before proceeding...

- [X] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [X] I read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [X] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up
- [X] I read through the recent [releases](https://github.com/PatrickF1/fzf.fish/releases) to make sure this is not simply a new feature

## Describe the bug
After installing `fzf.fish`, and updating the`Directory` keybinding to `CTRL + F`, I get the following error:
```
❯ fish: Unknown command: fd
in command substitution
	called on line 25 of file ~/projects/dotfiles/fish/functions/_fzf_search_directory.fish
in function '_fzf_search_directory'
~/projects/dotfiles/fish/functions/_fzf_search_directory.fish (line 25): Unknown command
        set -f file_paths_selected ($fd_cmd 2>/dev/null | _fzf_wrapper $fzf_arguments)
```

I had to update this keybinding because the keybindings using the `ALT` key do not work on my Mac for some reason. I was able to update and use every one _except_ for this one, where once I was able to update it to a keybinding that would work on my computer, I got the above error message.

If applicable, include screenshots here.

![image](https://github.com/PatrickF1/fzf.fish/assets/62859552/4a03ef35-75fb-4082-acf6-c27f14c03076)

## Steps to reproduce
- Install `fish` on an M1 mac with `homebrew` (`brew install fish`)
- Install `fisher`: `curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher`
- Install `fzf.fish` using this command: `fisher install PatrickF1/fzf.fish`

## Environment

Versions installed:

- Fish: 3.6.1
- fzf.fish: 9.9
- terminal: Mac Terminal (using `fish`)
- OS: MacOS 13.4.1

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set?
```
# in my 'config.fish'

fzf_configure_bindings --processes=\cp --git_status=\cs --git_log=\cl --directory=\ce

## Additional context

**Comment by PatrickF1** [comment]
Hi Drew, how did you install fd?

**Comment by Drew-Daniels** [comment]
Arg, sorry that was my mistake. Looks like it wasn't installed.

It was fixed as soon as I ran `brew install fd`.

Sorry about that, and thanks for the quick reply!

**Comment by PatrickF1** [comment]
No problem, it happens :)
