### ISSUE TITLE
Command history not working

### ISSUE THREAD

**Issue by anon-legion** [PatrickF1/fzf.fish#312]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [x] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up
- [x] I read through the recent [releases](https://github.com/PatrickF1/fzf.fish/releases) to make sure this is not simply a new feature

## Describe the bug
ctrl+r (command history) only creates a new line above my prompt and does not show any command history.

![fzf-fish_command_history_bug](https://github.com/PatrickF1/fzf.fish/assets/77139649/8ca1829f-a9c3-4f89-bd5e-b5669a2669fc)

## Steps to reproduce
Press ctrl+r

## Environment

Versions installed:

- Fish: 3.6.1
- fzf.fish: 10.0
- terminal: GNOME Terminal (Version 3.44.0 for GNOME 42)
- OS: Pop!_OS 22.04 LTS

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set?

I am using defaults except for `fzf_configure_bindings --directory=\cf` set in my `config.fish`

## Additional context
This is a fresh install for a brand new S76 laptop.
If I unbind command history by doing `fzf_configure_bindings --history=`,  triggers a different looking command history like so:
![fzf_configure_bindings_--history=](https://github.com/PatrickF1/fzf.fish/assets/77139649/08bcfd68-6f8d-42a2-ab76-4b9f3f602211)

**Comment by PatrickF1** [comment]
Hi, 

- can you run `bind` and paste the bottom lines that aren't default?
- Also check your GNOME Terminal if Ctrl+R is being set to something already?
- Do the other fzf.fish commands work?

**Comment by anon-legion** [comment]
Hi @PatrickF1,

1. The only non-default fzf.fish bind that I configured is Directory, set to `ctrl+f`. The results of `bind`:
![Screenshot from 2023-11-04 10-06-00](https://github.com/PatrickF1/fzf.fish/assets/77139649/c74c53e8-6292-44cb-846a-61aa321ba692)

2. GNOME Terminal > Preferences > Shortcuts has not binds for `Ctrl+R`, the only commands that start with `ctrl` are Zoom in (`ctrl++`), Zoom out (`ctrl+-`), Normal Size (`ctrl+0`), Switch to previous tab (`ctrl+page up`), and Switch to next tab (`ctrl+page down`). The rest start with either `shift`, `alt`, or are `disabled`

3. Yes the other fzf.fish commands works as expect. Directory, Process, etc... I am only having issue with History

**Comment by PatrickF1** [comment]
Okay. Can you try binding Ctrl+R to ls and see if it triggers ls
successfully?

And also run ‘history’ and make sure it’s not empty?

**Comment by anon-legion** [comment]
I bind `ctrl+r` to `ls` in `config.fish` like so:
![Screenshot from 2023-11-05 08-49-06](https://github.com/PatrickF1/fzf.fish/assets/77139649/3c05fbc5-8b89-40f7-ae07-46098b0b8239)

Pressing `ctrl+r` triggers `ls` as expected:
![Screenshot from 2023-11-05 08-52-04](https://github.com/PatrickF1/fzf.fish/assets/77139649/abb2b0c4-0234-48bb-9e2b-26c04c695597)


Running `history` shows history is not empty:
![Screenshot from 2023-11-05 08-53-52](https://github.com/PatrickF1/fzf.fish/assets/77139649/e29ffb51-f874-44a4-b886-c1d0c72c8938)

**Comment by PatrickF1** [comment]
Wow, very strange indeed. Can you try using a different terminal emulator and seeing it it works there? I'm trying to isolate the bug.

And if that still doesn't work, can you go into `_fzf_search_history` and overwrite the file to do something really simply like this
```
function _fzf_search_history
    set -f commands_selected (ls | _fzf_wrapper)
    if test $status -eq 0
        commandline --replace -- $commands_selected
    end

    commandline --function repaint
end
```
You can the path to the file is by running `functions _fzf_search_history`.

Sorry you have to get your hands dirty. This is a tricky bug.

**Comment by anon-legion** [comment]
1. Tried using a different terminal (Guake Terminal) and the same issue persist, pressing `ctrl+r` creates a newline above my prompt:
![Screenshot from 2023-11-05 20-23-46](https://github.com/PatrickF1/fzf.fish/assets/77139649/51088698-166c-4d52-9781-7d61e29f534d)


2. Copy pasted suggested code to `_fzf_search_history.fish` and overwrote existing code like so:
![Screenshot from 2023-11-05 20-47-44](https://github.com/PatrickF1/fzf.fish/assets/77139649/e6d576b1-b4d5-4eff-a6fe-9e6f7496204b)


The results of pressing `ctrl+r` now yields the contents of the path directory:
![Screenshot from 2023-11-05 20-51-45](https://github.com/PatrickF1/fzf.fish/assets/77139649/3bd1b59b-546c-4d88-a201-382120d35cc5)

**Comment by PatrickF1** [comment]
Ok we've isolated the issue to something within `_fzf_search_history`.

One more test:
this time replace `_fzf_search_history` with

```
function _fzf_search_history
    set -f commands_selected (history | _fzf_wrapper)
    if test $status -eq 0
        commandline --replace -- $commands_selected
    end

    commandline --function repaint
end
```
does that work?

**Comment by anon-legion** [comment]
I copy pasted your code and replaced `_fzf_search_history` as you requested:
![Screenshot from 2023-11-06 20-44-43](https://github.com/PatrickF1/fzf.fish/assets/77139649/40711755-6489-4b36-a560-2991fab64c4d)

Pressing `ctrl+r` now shows command history like so:
![Screenshot from 2023-11-06 20-44-15](https://github.com/PatrickF1/fzf.fish/assets/77139649/ea90be16-a71e-43e4-89c1-ed159b9e0a94)


Did we fix it? Or are we close?

**Comment by PatrickF1** [comment]
I think we're close-ish. We've eliminated a lot of things as the problem and know the problem is something in `_fzf_search_history`. Still don't know exactly what it is though.

You seem like a very competent user. Would you prefer to play around with `_fzf_search_history` and debug it yourself now, or do you want me to continue debugging over this conversation? Obviously it'll be more thinking for you to do the former but it'll also be way faster.

**Comment by anon-legion** [comment]
I will give it a shot. I'll see what I can do and work on it this weekend when I have no work so I have plenty time to sit down and thoroughly debug the issue. If I have any questions or if I find the solution I will be posting it here.

**Comment by anon-legion** [comment]
Hi @PatrickF1, I Have isolated the issue to the `--scheme=history` option of the `_fzf_wrapper` function.
Currently my `_fzf_search_history.fish` is exactly like the default fish function except with the `--scheme=history` commented out like so:
```
function _fzf_search_history --description "Search command history. Replace the command line with the selected command."
    if test -z "$fish_private_mode"
        builtin history merge
    end

    if not set --query fzf_history_time_format
        set -f fzf_history_time_format "%m-%d %H:%M:%S"
    end

    set -f time_prefix_regex '^.*? │ '

    set -f commands_selected (
        builtin history --null --show-time="$fzf_history_time_format │ " |
        _fzf_wrapper --read0 \
            --print0 \
            --multi \
        #     --scheme=history \
            --prompt="History> " \
            --query=(commandline) \
            --preview="string replace --regex '$time_prefix_regex' '' -- {} | fish_indent --ansi" \
            --preview-window="bottom:3:wrap" \
            $fzf_history_opts |
        string split0 |
        string replace --regex $time_prefix_regex ''
    )

    if test $status -eq 0
        commandline --replace -- $commands_selected
    end

    commandline --function repaint
end
```

Now pressing `ctrl+r` show the command history and it looks to me like its working normally now? What was that option supposed to do?
![Screenshot from 2023-11-11 18-54-16](https://github.com/PatrickF1/fzf.fish/assets/77139649/6f51cc7a-12c9-4327-bffb-ce23641a794a)

**Comment by PatrickF1** [comment]
https://github.com/PatrickF1/fzf.fish/pull/302 is where it was added. It makes the scoring algorithm better for chronological list. Your issue might be that you're not on the latest version of fzf, but for some reason the error isn't showing up!

**Comment by anon-legion** [comment]
Oh please pardon me. I installed fzf  using apt repo and I did not realize until I looked at "Packaging status" that the version it downloads for Ubuntu 22.04 is very far behind (0.29.0), I should have not made any assumptions regarding the recency of the package's version. I have downloaded and built fzf from source and I am now on the latest version (0.43.0).
I have also uncommented the `-scheme=history` option in `_fzf_search_history.fish` and now everything works as expected.
Thank you for your patience.

**Comment by anon-legion** [comment]
Oh please pardon me. I installed fzf using apt repo and I did not realize until I looked at "Packaging status" that the version it downloads for Ubuntu 22.04 is very far behind (0.29.0), I should have not made any assumptions regarding the recency of the package's version. I have downloaded and built fzf from source and I am now on the latest version (0.43.0).
I have also uncommented the -scheme=history option in _fzf_search_history.fish and now everything works as expected.
Thank you for your patience.

**Comment by PatrickF1** [comment]
No problem, it happens! I am also very confused why it doesn't error and just outputs a newline. Let me know if you have any ideas!
