### ISSUE TITLE
fish: No matches for wildcard '^.*?'

### ISSUE THREAD

**Issue by Fissium** [PatrickF1/fzf.fish#314]
## Before proceeding...

- [x] My CLIs meet the [minimum version requirements](https://github.com/PatrickF1/fzf.fish#installation)
- [x] I read through the [troubleshooting guide](https://github.com/PatrickF1/fzf.fish/wiki/Troubleshooting)
- [x] If I updated fzf.fish for the first time in over 6 months, I read the [migration guides](https://github.com/PatrickF1/fzf.fish/wiki/Migration-Guides) to make sure I'm caught up
- [x] I read through the recent [releases](https://github.com/PatrickF1/fzf.fish/releases) to make sure this is not simply a new feature

## Describe the bug

The search history command preview window returns the following error
![Screenshot from 2023-11-06 14-22-08](https://github.com/PatrickF1/fzf.fish/assets/35971213/ef2a18e0-db4f-47d3-a731-ea9e39f47879)

## Steps to reproduce
Install fzf.fish plugin via `fisher install PatrickF1/fzf.fish`.
Use `CTRL-R` to search through history.

## Environment

Versions installed:

- Fish: 3.6.1
- fzf.fish: 10.1
- terminal: Alacritty/tmux
- OS: Fedora Linux 38

Which, if any, [configuration variables](https://github.com/PatrickF1/fzf.fish#configuration) such as `fzf_preview_file_cmd` are set? None

## Additional context
installed the plugin for the first time.

**Comment by PatrickF1** [comment]
Hi, does this error occur after as soon as you open up Search History, or after you select some stuff and hit enter?

**Comment by Fissium** [comment]
@PatrickF1 As soon as I open up search history.

**Comment by PatrickF1** [comment]
Could you temporarily switch back to version 10.0 and tell if there was still an issue, please?

**Comment by Fissium** [comment]
@PatrickF1 version 10.0 works as expected!

**Comment by PatrickF1** [comment]
Can you update and try again? Sorry that was a bug I should've caught if I was more careful.

**Comment by Fissium** [comment]
@PatrickF1 Now it works :) Thank you!
