### ISSUE TITLE
Open file in EDITOR

### ISSUE THREAD

**Issue by 037g** [PatrickF1/fzf.fish#84]
Hi,

Thank you so much for making this.

Previously, I could use CTRL-O and it would let me open a file in the system editor. This does not seem to be available anymore. Can you please help direct me to the best way to accomplish this?

When I add this `bind --mode insert \co '__fzf_open --editor'` in my `conf.d/fzf.fish`
I get: `fish: Unknown command: __fzf_open`

Thank You

**Comment by PatrickF1** [comment]
I didn't implement that. The closest thing is to use type `vim` or whatever you use and then hit Ctrl+F. I'm not going to implement a tool just for opening files because I want the commands to be composable. Sorry about that.
