### ISSUE TITLE
file paths doesn't work with tilde ~ prefix

### ISSUE THREAD

**Issue by arthurk** [PatrickF1/fzf.fish#88]
For example `vim ~/<ctrl-f>` does not work. When I expand the path (`vim /Users/aaa/<ctrl-f>`) it works fine. It would be great if this feature could be added.

Using fish 3.1.2 and fzf.fish 5.3

**Comment by PatrickF1** [comment]
Hi @arthurk! Thanks for reporting this bug. You are right--when @kidonng and I worked on this, we didn't do anything to automatically expand the ~. Give us some time to fix it. Thanks again.

**Comment by kidonng** [comment]
Guess what, I just stumbled upon this issue myself and then I saw this issue 😄

**Comment by arthurk** [comment]
This works great, thanks for fixing it!
